[general]
import = ["~/.config/alacritty/dracula.toml"]

[env]
TERM = "xterm-256color"
# X11: Disable annoying display scaling
#WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 9

# Change font, must be installed first
#[font.normal]
#family = "MesloLGS NF"
#style = "Regular"

# Windows: Use some BASH shell instead of Windows Command Prompt
#[terminal.shell]
#program = "C:\\Program Files\\Git\\bin\\bash.exe"
#args = ["--cd-to-home"]
