export ZSH="/home/hon/.oh-my-zsh"

CASE_SENSITIVE="true"
ENABLE_CORRECTION="false"
UPDATE_ZSH_DAYS=7

plugins=(git)

ZSH_THEME="powerlevel9k/powerlevel9k"
POWERLEVEL9K_MODE="nerdfont-complete"
POWERLEVEL9K_DISABLE_RPROMPT="true"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(root_indicator dir dir_writable vcs)
POWERLEVEL9K_STATUS_CROSS="true"

# At the end
source $ZSH/oh-my-zsh.sh
